
'use client';

import { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { PlusCircle, Edit, Trash2, AlertTriangle, Loader2, UserPlus, Users, Phone, HomeIcon, Star, IndianRupee, ArrowRight } from 'lucide-react'; // Added relevant icons
import { getAuthHeaders } from '@/lib/auth';
import { format } from 'date-fns';
import { Types } from 'mongoose'; // Import Types
import Link from 'next/link';
import { cn } from '@/lib/utils';

// Use NEXT_PUBLIC_ prefix for client-side environment variables
const API_URL = process.env.NEXT_PUBLIC_API_URL;

interface Customer {
  _id: string;
  name: string;
  phone: string;
  address?: string;
  trustScore: number;
  creditLimit: number;
  createdAt: string; // ISO String dates from API
  updatedAt: string;
}

// Form data type excludes fields generated by backend
type CustomerFormData = Omit<Customer, '_id' | 'createdAt' | 'updatedAt'>;

export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [formData, setFormData] = useState<CustomerFormData>({
    name: '',
    phone: '',
    address: '',
    trustScore: 5, // Default value
    creditLimit: 0, // Default value
  });
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [customerToDelete, setCustomerToDelete] = useState<Customer | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);


  const fetchCustomers = useCallback(async () => {
    if (!API_URL) {
        setError("API URL is not configured. Please check environment variables.");
        setLoading(false);
        return;
    }
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_URL}/customers`, {
        headers: getAuthHeaders(), // Get JWT token header
      });
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ message: 'Failed to parse error response' }));
        throw new Error(errorData.message || `Failed to fetch customers (${response.status})`);
      }
      const data: Customer[] = await response.json();
      setCustomers(data);
    } catch (err: any) {
        console.error("Fetch Customers Error:", err);
        setError(err.message || 'An unknown error occurred while fetching customers.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
     if (typeof window !== 'undefined') {
         const hash = window.location.hash;
         if (hash === '#add') {
             handleOpenForm();
             // Optionally remove hash to prevent re-opening on refresh
             window.history.replaceState(null, '', window.location.pathname + window.location.search);
         }
     }
    fetchCustomers();
  }, [fetchCustomers]); // fetchCustomers is stable due to useCallback


  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      // Convert to number for specific fields, handle potential NaN
      [name]: name === 'trustScore' || name === 'creditLimit' ? (value === '' ? '' : Number(value)) : value,
    }));
  };

  const resetForm = () => {
    setEditingCustomer(null);
    setFormData({
        name: '',
        phone: '',
        address: '',
        trustScore: 5,
        creditLimit: 0,
    });
    setFormError(null);
    setIsSubmitting(false); // Ensure submitting state is reset
  };

  const handleOpenForm = (customer: Customer | null = null) => {
      resetForm(); // Reset form state before opening
      if (customer) {
          setEditingCustomer(customer);
          setFormData({
              name: customer.name,
              phone: customer.phone,
              address: customer.address || '',
              trustScore: customer.trustScore,
              creditLimit: customer.creditLimit,
          });
      }
      setIsFormOpen(true);
  };

  const handleCloseForm = () => {
      // Prevent closing if submitting
      if (isSubmitting) return;
      setIsFormOpen(false);
      // Delay reset slightly to allow dialog closing animation
      setTimeout(resetForm, 300);
  };


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!API_URL) {
        setFormError("API URL not configured.");
        return;
    }
    setFormError(null); // Clear previous form errors
    setIsSubmitting(true);

    // --- Form Validation ---
    if (!formData.name || !formData.phone) {
        setFormError('Name and Phone are required.');
        setIsSubmitting(false);
        return;
    }
     const trustScoreNum = Number(formData.trustScore);
     if (isNaN(trustScoreNum) || trustScoreNum < 0 || trustScoreNum > 10) {
        setFormError('Trust Score must be a number between 0 and 10.');
        setIsSubmitting(false);
        return;
     }
     const creditLimitNum = Number(formData.creditLimit);
     if (isNaN(creditLimitNum) || creditLimitNum < 0) {
        setFormError('Credit Limit must be a non-negative number.');
        setIsSubmitting(false);
        return;
     }
     // Basic Indian phone number format check (optional, can be more robust)
     if (!/^[6-9]\d{9}$/.test(formData.phone.replace(/\s+/g, ''))) {
         setFormError('Please enter a valid 10-digit Indian mobile number.');
         setIsSubmitting(false);
         return;
     }

    const url = editingCustomer
      ? `${API_URL}/customers/${editingCustomer._id}`
      : `${API_URL}/customers`;
    const method = editingCustomer ? 'PUT' : 'POST';

    const bodyPayload = {
        ...formData,
        trustScore: trustScoreNum,
        creditLimit: creditLimitNum,
        phone: formData.phone.replace(/\s+/g, ''), // Clean phone number before sending
    };


    try {
      const response = await fetch(url, {
        method: method,
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify(bodyPayload),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ message: 'Failed to parse error response' }));
        // Check for specific duplicate phone error if backend provides it
        if (response.status === 409 || (response.status === 400 && errorData.message?.toLowerCase().includes('phone'))) {
             throw new Error(`Phone number ${formData.phone} might already be registered.`);
        }
        throw new Error(errorData.message || `Failed to ${editingCustomer ? 'update' : 'add'} customer (${response.status})`);
      }

      await fetchCustomers(); // Refresh the customer list
      handleCloseForm(); // Close the form on success

    } catch (err: any) {
      console.error("Submit Customer Error:", err);
      setFormError(err.message || `An unknown error occurred.`);
    } finally {
      setIsSubmitting(false); // Re-enable form after attempt
    }
  };

  const openDeleteDialog = (customer: Customer) => {
      setCustomerToDelete(customer);
      setIsDeleteDialogOpen(true);
  };

  const closeDeleteDialog = () => {
       if (isDeleting) return; // Prevent closing while deletion is in progress
      setIsDeleteDialogOpen(false);
       // Delay resetting state slightly
       setTimeout(() => {
          setCustomerToDelete(null);
          // Do not reset isDeleting here, it's reset in handleDelete finally block
       }, 300);
  };

  const handleDelete = async () => {
      if (!customerToDelete || !API_URL) return;
      setIsDeleting(true);
      setError(null); // Clear main page error

      try {
          const response = await fetch(`${API_URL}/customers/${customerToDelete._id}`, {
              method: 'DELETE',
              headers: getAuthHeaders(),
          });

          if (!response.ok) {
              const errorData = await response.json().catch(() => ({ message: 'Failed to parse error response' }));
               // Specific check for constraint violation (customer has loans)
               if (response.status === 400 && errorData.message?.includes('loan')) { // Check for 'loan'
                    setError(`Cannot delete "${customerToDelete.name}": ${errorData.message}`);
               } else {
                   throw new Error(errorData.message || `Failed to delete customer (${response.status})`);
               }
               closeDeleteDialog(); // Close dialog even on specific errors like having loans
               return; // Stop further execution for this specific error
          }

          // Remove customer from state optimistically or refetch
           setCustomers(prev => prev.filter(c => c._id !== customerToDelete._id));
           // Or await fetchCustomers();
          closeDeleteDialog(); // Close dialog on successful deletion

      } catch (err: any) {
          console.error("Delete Customer Error:", err);
           // Show error on the main page
           setError(`Delete failed: ${err.message}`);
           closeDeleteDialog(); // Close dialog on general errors
      } finally {
          setIsDeleting(false); // Ensure deleting state is always reset
      }
  };

  // Helper to format currency
   const formatCurrency = (amount: number | null | undefined): string => {
     if (amount === null || amount === undefined) return '₹ --.--';
     return `₹${Number(amount).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
   };


  return (
    <div className="container mx-auto py-6 px-4 md:px-6 space-y-8">
      {/* Main Error Alert */}
      {error && (
        <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>
                {error}
                 {/* Add retry button only for fetch errors */}
                 {error.includes('fetch customers') &&
                    <Button variant="link" size="sm" onClick={fetchCustomers} className="p-0 h-auto ml-2">Retry</Button>}
            </AlertDescription>
        </Alert>
      )}

      <Card className="shadow-md rounded-lg overflow-hidden border border-border">
        <CardHeader className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 bg-card border-b">
          <div>
            <CardTitle className="text-2xl font-bold flex items-center gap-2"><Users className="h-6 w-6 text-primary"/> Manage Customers</CardTitle>
            <CardDescription className="text-muted-foreground mt-1">Add, view, edit, or delete customer profiles.</CardDescription>
          </div>
          {/* Add Customer Dialog */}
          <Dialog open={isFormOpen} onOpenChange={(open) => open ? setIsFormOpen(true) : handleCloseForm()}>
                <DialogTrigger asChild>
                    {/* Ensure the button click explicitly calls handleOpenForm without arguments for adding new */}
                    <Button onClick={() => handleOpenForm()}>
                        <UserPlus className="mr-2 h-4 w-4" /> Add Customer
                    </Button>
                </DialogTrigger>
                 {/* Dialog Content for Add/Edit */}
                <DialogContent
                    className="sm:max-w-[520px]"
                    onInteractOutside={(e) => { if (isSubmitting) e.preventDefault(); }}
                    onEscapeKeyDown={(e) => { if (isSubmitting) e.preventDefault(); }}
                >
                    <DialogHeader>
                        <DialogTitle className="text-xl">{editingCustomer ? 'Edit Customer Details' : 'Add New Customer'}</DialogTitle>
                    </DialogHeader>
                    {/* Form inside the dialog */}
                    <form onSubmit={handleSubmit} className="space-y-5 pt-4 max-h-[70vh] overflow-y-auto pr-2">
                        {/* Name Input */}
                        <div className="space-y-2">
                           <Label htmlFor="name">Full Name <span className="text-destructive">*</span></Label>
                           <Input id="name" name="name" value={formData.name} onChange={handleInputChange} required disabled={isSubmitting} placeholder="e.g., John Doe" className="text-base"/>
                        </div>
                        {/* Phone Input */}
                        <div className="space-y-2">
                            <Label htmlFor="phone">Mobile Number <span className="text-destructive">*</span></Label>
                             <div className="relative">
                                <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                                <Input id="phone" name="phone" type="tel" value={formData.phone} onChange={handleInputChange} required disabled={isSubmitting} placeholder="e.g., 9876543210" className="pl-10 text-base"/>
                             </div>
                             <p className="text-xs text-muted-foreground">Enter a 10-digit Indian mobile number.</p>
                        </div>
                        {/* Address Textarea */}
                        <div className="space-y-2">
                           <Label htmlFor="address">Address</Label>
                           <Textarea id="address" name="address" value={formData.address ?? ''} onChange={handleInputChange} disabled={isSubmitting} placeholder="Optional: House No, Street, Area, City" rows={3}/>
                        </div>
                        {/* Trust Score and Credit Limit Inputs */}
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="trustScore">Trust Score (0-10)</Label>
                                <div className="relative">
                                  <Star className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                                  <Input id="trustScore" name="trustScore" type="number" min="0" max="10" value={formData.trustScore} onChange={handleInputChange} required disabled={isSubmitting} className="pl-10"/>
                                </div>
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="creditLimit">Credit Limit</Label>
                                <div className="relative">
                                   <IndianRupee className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                                   <Input id="creditLimit" name="creditLimit" type="number" min="0" step="any" value={formData.creditLimit} onChange={handleInputChange} required disabled={isSubmitting} placeholder="e.g., 5000" className="pl-10"/>
                                </div>
                           </div>
                        </div>

                        {/* Form Error Alert */}
                       {formError && (
                           <Alert variant="destructive">
                               <AlertTriangle className="h-4 w-4" />
                               <AlertTitle>Error</AlertTitle>
                               <AlertDescription>{formError}</AlertDescription>
                           </Alert>
                       )}
                       {/* Dialog Footer with Actions */}
                       <DialogFooter className="pt-5 sticky bottom-0 bg-background py-4 border-t">
                           <Button type="button" variant="outline" onClick={handleCloseForm} disabled={isSubmitting}>Cancel</Button>
                           <Button type="submit" disabled={isSubmitting}>
                              {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                              {editingCustomer ? 'Save Changes' : 'Add Customer'}
                           </Button>
                       </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </CardHeader>
        {/* Customer Table Content */}
        <CardContent className="p-0">
          {loading ? (
             <div className="flex justify-center items-center py-20 text-muted-foreground">
                <Loader2 className="mr-2 h-5 w-5 animate-spin text-primary" />
                 <span>Loading customers...</span>
             </div>
          ) : customers.length === 0 ? (
              // Empty State Message
              <div className="text-center py-20 px-6 bg-muted/30">
                 <Users className="mx-auto h-16 w-16 text-muted-foreground/40 mb-5" />
                 <p className="text-xl font-semibold text-foreground mb-2">No Customers Found</p>
                 <p className="text-muted-foreground text-sm mb-6 max-w-xs mx-auto">It looks like you haven't added any customers yet. Add your first customer to start tracking loans.</p>
                 {/* Button to open the add form */}
                 <Button onClick={() => handleOpenForm()}>
                    <UserPlus className="mr-2 h-4 w-4" /> Add First Customer
                 </Button>
             </div>
          ) : (
            // Customer Table
            <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="pl-6">Name</TableHead>
                      <TableHead><Phone className="inline-block h-4 w-4 mr-1"/>Phone</TableHead>
                      <TableHead className="hidden md:table-cell"><HomeIcon className="inline-block h-4 w-4 mr-1"/>Address</TableHead>
                      <TableHead className="text-center"><Star className="inline-block h-4 w-4 mr-1"/>Trust</TableHead>
                      <TableHead className="text-right"><IndianRupee className="inline-block h-4 w-4 mr-1"/>Credit Limit</TableHead>
                       <TableHead className="hidden lg:table-cell text-right pr-6">Added On</TableHead>
                      {/* Sticky Actions Column */}
                      <TableHead className="text-right sticky right-0 bg-card z-10 px-4">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {customers.map((customer) => (
                      <TableRow key={customer._id} className="group hover:bg-muted/50">
                        <TableCell className="font-medium pl-6">{customer.name}</TableCell>
                        <TableCell>{customer.phone}</TableCell>
                        <TableCell className="hidden md:table-cell max-w-xs truncate text-muted-foreground">{customer.address || '--'}</TableCell>
                        <TableCell className="text-center font-medium">{customer.trustScore}/10</TableCell>
                        <TableCell className="text-right">{formatCurrency(customer.creditLimit)}</TableCell>
                        <TableCell className="hidden lg:table-cell text-right text-sm text-muted-foreground pr-6">
                            {format(new Date(customer.createdAt), 'dd MMM yyyy')}
                        </TableCell>
                        {/* Action Buttons - Sticky */}
                        <TableCell className="text-right space-x-1 sticky right-0 bg-card group-hover:bg-muted/50 transition-colors z-10 px-4">
                             {/* Edit Button */}
                             <Button variant="ghost" size="icon" className="hover:text-primary h-8 w-8" onClick={() => handleOpenForm(customer)} title="Edit">
                                 <Edit className="h-4 w-4" />
                                  <span className="sr-only">Edit</span>
                             </Button>
                             {/* Delete Button */}
                             <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive/80 hover:bg-destructive/10 h-8 w-8" onClick={() => openDeleteDialog(customer)} title="Delete">
                                 <Trash2 className="h-4 w-4" />
                                  <span className="sr-only">Delete</span>
                             </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
            </div>
           )}
        </CardContent>
         {/* Optional: Add pagination controls if list becomes long */}
         {customers.length > 10 && (
            <CardFooter className="p-4 border-t justify-center text-sm text-muted-foreground">
                {/* Placeholder for pagination */}
                Displaying {customers.length} customers. {/* Add pagination component later */}
            </CardFooter>
          )}
      </Card>


      {/* Delete Confirmation Dialog */}
       <Dialog open={isDeleteDialogOpen} onOpenChange={(open) => open ? setIsDeleteDialogOpen(true) : closeDeleteDialog()}>
         <DialogContent
             className="sm:max-w-md"
             onInteractOutside={(e) => { if (isDeleting) e.preventDefault(); }}
             onEscapeKeyDown={(e) => { if (isDeleting) e.preventDefault(); }}
         >
             <DialogHeader>
                 <DialogTitle className="flex items-center gap-2 text-lg"><AlertTriangle className="h-5 w-5 text-destructive"/> Confirm Deletion</DialogTitle>
             </DialogHeader>
             <div className="py-4">
                <p className="text-sm text-muted-foreground">
                    Are you sure you want to permanently delete the customer <strong className="text-foreground">"{customerToDelete?.name}"</strong>?
                </p>
                <p className="text-sm text-destructive mt-2">
                    This action cannot be undone. Ensure the customer has no outstanding loans before deleting.
                </p>
             </div>
             {/* Dialog Footer for Delete Confirmation */}
             <DialogFooter className="mt-2">
                <Button variant="outline" onClick={closeDeleteDialog} disabled={isDeleting}>Cancel</Button>
                <Button variant="destructive" onClick={handleDelete} disabled={isDeleting}>
                    {isDeleting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    {isDeleting ? 'Deleting...' : 'Delete Customer'}
                </Button>
             </DialogFooter>
         </DialogContent>
       </Dialog>
    </div>
  );
}

    