
'use client';

import { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { PlusCircle, Edit, Trash2, AlertTriangle, Loader2, UserPlus, Users } from 'lucide-react';
import { getAuthHeaders } from '@/lib/auth';
import { format } from 'date-fns';
import { Types } from 'mongoose'; // Import Types

// Use NEXT_PUBLIC_ prefix for client-side environment variables
const API_URL = process.env.NEXT_PUBLIC_API_URL; // Corrected variable name

interface Customer {
  _id: string; // Keep as string for frontend use
  name: string;
  phone: string;
  address?: string;
  trustScore: number;
  creditLimit: number;
  createdAt: string; // ISO String dates from API
  updatedAt: string;
}

// Form data type excludes fields generated by backend
type CustomerFormData = Omit<Customer, '_id' | 'createdAt' | 'updatedAt'>;

export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [formData, setFormData] = useState<CustomerFormData>({
    name: '',
    phone: '',
    address: '',
    trustScore: 5, // Default value
    creditLimit: 0, // Default value
  });
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [customerToDelete, setCustomerToDelete] = useState<Customer | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);


  const fetchCustomers = useCallback(async () => {
    if (!API_URL) {
        setError("API URL is not configured. Please check environment variables.");
        setLoading(false);
        return;
    }
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_URL}/customers`, {
        headers: getAuthHeaders(), // Get JWT token header
      });
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ message: 'Failed to parse error response' }));
        throw new Error(errorData.message || `Failed to fetch customers (${response.status})`);
      }
      const data: Customer[] = await response.json();
      setCustomers(data);
    } catch (err: any) {
        console.error("Fetch Customers Error:", err);
        setError(err.message || 'An unknown error occurred while fetching customers.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
     if (typeof window !== 'undefined') {
         const hash = window.location.hash;
         if (hash === '#add') {
             handleOpenForm();
             // Optionally remove hash to prevent re-opening on refresh
             // window.history.replaceState(null, '', window.location.pathname + window.location.search);
         }
     }
    fetchCustomers();
  }, [fetchCustomers]); // fetchCustomers is stable due to useCallback


  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      // Convert to number for specific fields, handle potential NaN
      [name]: name === 'trustScore' || name === 'creditLimit' ? (value === '' ? '' : Number(value)) : value,
    }));
  };

  const resetForm = () => {
    setEditingCustomer(null);
    setFormData({
        name: '',
        phone: '',
        address: '',
        trustScore: 5,
        creditLimit: 0,
    });
    setFormError(null);
    setIsSubmitting(false); // Ensure submitting state is reset
  };

  const handleOpenForm = (customer: Customer | null = null) => {
      resetForm(); // Reset form state before opening
      if (customer) {
          setEditingCustomer(customer);
          setFormData({
              name: customer.name,
              phone: customer.phone,
              address: customer.address || '',
              trustScore: customer.trustScore,
              creditLimit: customer.creditLimit,
          });
      }
      setIsFormOpen(true);
  };

  const handleCloseForm = () => {
      // Prevent closing if submitting
      if (isSubmitting) return;
      setIsFormOpen(false);
      // Delay reset slightly to allow dialog closing animation
      setTimeout(resetForm, 300);
  };


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!API_URL) {
        setFormError("API URL not configured.");
        return;
    }
    setFormError(null); // Clear previous form errors
    setIsSubmitting(true);

    // --- Form Validation ---
    if (!formData.name || !formData.phone) {
        setFormError('Name and Phone are required.');
        setIsSubmitting(false);
        return;
    }
     const trustScoreNum = Number(formData.trustScore);
     if (isNaN(trustScoreNum) || trustScoreNum < 0 || trustScoreNum > 10) {
        setFormError('Trust Score must be a number between 0 and 10.');
        setIsSubmitting(false);
        return;
     }
     const creditLimitNum = Number(formData.creditLimit);
     if (isNaN(creditLimitNum) || creditLimitNum < 0) {
        setFormError('Credit Limit must be a non-negative number.');
        setIsSubmitting(false);
        return;
     }
     // Add phone number format validation if desired

    const url = editingCustomer
      ? `${API_URL}/customers/${editingCustomer._id}`
      : `${API_URL}/customers`;
    const method = editingCustomer ? 'PUT' : 'POST';

    const bodyPayload = {
        ...formData,
        trustScore: trustScoreNum,
        creditLimit: creditLimitNum,
    };


    try {
      const response = await fetch(url, {
        method: method,
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify(bodyPayload),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ message: 'Failed to parse error response' }));
        throw new Error(errorData.message || `Failed to ${editingCustomer ? 'update' : 'add'} customer (${response.status})`);
      }

      await fetchCustomers(); // Refresh the customer list
      handleCloseForm(); // Close the form on success

    } catch (err: any) {
      console.error("Submit Customer Error:", err);
      setFormError(err.message || `An unknown error occurred.`);
    } finally {
      setIsSubmitting(false); // Re-enable form after attempt
    }
  };

  const openDeleteDialog = (customer: Customer) => {
      setCustomerToDelete(customer);
      setIsDeleteDialogOpen(true);
  };

  const closeDeleteDialog = () => {
       if (isDeleting) return; // Prevent closing while deletion is in progress
      setIsDeleteDialogOpen(false);
       // Delay resetting state slightly
       setTimeout(() => {
          setCustomerToDelete(null);
          // Do not reset isDeleting here, it's reset in handleDelete finally block
       }, 300);
  };

  const handleDelete = async () => {
      if (!customerToDelete || !API_URL) return;
      setIsDeleting(true);
      setError(null); // Clear main page error

      try {
          const response = await fetch(`${API_URL}/customers/${customerToDelete._id}`, {
              method: 'DELETE',
              headers: getAuthHeaders(),
          });

          if (!response.ok) {
              const errorData = await response.json().catch(() => ({ message: 'Failed to parse error response' }));
               // Specific check for constraint violation (customer has loans)
               if (response.status === 400 && errorData.message?.includes('loans')) {
                    setError(`Cannot delete "${customerToDelete.name}": ${errorData.message}`);
               } else {
                   throw new Error(errorData.message || `Failed to delete customer (${response.status})`);
               }
               closeDeleteDialog(); // Close dialog even on specific errors like having loans
               return; // Stop further execution for this specific error
          }

          // Remove customer from state optimistically or refetch
           setCustomers(prev => prev.filter(c => c._id !== customerToDelete._id));
           // Or await fetchCustomers();
          closeDeleteDialog(); // Close dialog on successful deletion

      } catch (err: any) {
          console.error("Delete Customer Error:", err);
           // Show error on the main page
           setError(err.message || 'An unknown error occurred while deleting.');
           closeDeleteDialog(); // Close dialog on general errors
      } finally {
          setIsDeleting(false); // Ensure deleting state is always reset
      }
  };

  return (
    <div className="container mx-auto py-6 px-4 md:px-6 space-y-6">
      {/* Main Error Alert */}
      {error && (
        <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>
                {error}
                 {/* Add retry button only for fetch errors */}
                 {error.includes('fetch customers') &&
                    <Button variant="link" size="sm" onClick={fetchCustomers} className="p-0 h-auto ml-2">Retry</Button>}
            </AlertDescription>
        </Alert>
      )}

      <Card className="shadow-md rounded-lg overflow-hidden border border-border">
        <CardHeader className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 bg-card border-b">
          <div>
            <CardTitle className="text-xl font-semibold flex items-center gap-2"><Users className="h-5 w-5 text-primary"/> Manage Customers</CardTitle>
            <CardDescription className="text-muted-foreground mt-1">Add, view, edit, or delete customer profiles.</CardDescription>
          </div>
          {/* Add Customer Dialog */}
          <Dialog open={isFormOpen} onOpenChange={(open) => open ? setIsFormOpen(true) : handleCloseForm()}>
                <DialogTrigger asChild>
                    {/* Ensure the button click explicitly calls handleOpenForm without arguments for adding new */}
                    <Button onClick={() => handleOpenForm()}>
                        <UserPlus className="mr-2 h-4 w-4" /> Add Customer
                    </Button>
                </DialogTrigger>
                 {/* Dialog Content for Add/Edit */}
                <DialogContent
                    className="sm:max-w-[480px]"
                    onInteractOutside={(e) => { if (isSubmitting) e.preventDefault(); }}
                    onEscapeKeyDown={(e) => { if (isSubmitting) e.preventDefault(); }}
                >
                    <DialogHeader>
                        <DialogTitle>{editingCustomer ? 'Edit Customer' : 'Add New Customer'}</DialogTitle>
                    </DialogHeader>
                    {/* Form inside the dialog */}
                    <form onSubmit={handleSubmit} className="space-y-4 pt-4">
                        {/* Name Input */}
                        <div className="space-y-2">
                           <Label htmlFor="name">Name <span className="text-destructive">*</span></Label>
                           <Input id="name" name="name" value={formData.name} onChange={handleInputChange} required disabled={isSubmitting} placeholder="e.g., John Doe"/>
                        </div>
                        {/* Phone Input */}
                        <div className="space-y-2">
                            <Label htmlFor="phone">Phone <span className="text-destructive">*</span></Label>
                            <Input id="phone" name="phone" value={formData.phone} onChange={handleInputChange} required disabled={isSubmitting} placeholder="e.g., 9876543210"/>
                        </div>
                        {/* Address Textarea */}
                        <div className="space-y-2">
                           <Label htmlFor="address">Address</Label>
                           <Textarea id="address" name="address" value={formData.address ?? ''} onChange={handleInputChange} disabled={isSubmitting} placeholder="Optional: Customer's address"/>
                        </div>
                        {/* Trust Score and Credit Limit Inputs */}
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="trustScore">Trust Score (0-10)</Label>
                                <Input id="trustScore" name="trustScore" type="number" min="0" max="10" value={formData.trustScore} onChange={handleInputChange} required disabled={isSubmitting} />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="creditLimit">Credit Limit (₹)</Label>
                                <Input id="creditLimit" name="creditLimit" type="number" min="0" step="any" value={formData.creditLimit} onChange={handleInputChange} required disabled={isSubmitting} placeholder="e.g., 5000" />
                           </div>
                        </div>

                        {/* Form Error Alert */}
                       {formError && (
                           <Alert variant="destructive">
                               <AlertTriangle className="h-4 w-4" />
                               <AlertTitle>Form Error</AlertTitle>
                               <AlertDescription>{formError}</AlertDescription>
                           </Alert>
                       )}
                       {/* Dialog Footer with Actions */}
                       <DialogFooter className="pt-4">
                           <DialogClose asChild>
                              <Button type="button" variant="outline" onClick={handleCloseForm} disabled={isSubmitting}>Cancel</Button>
                           </DialogClose>
                           <Button type="submit" disabled={isSubmitting}>
                              {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                              {editingCustomer ? 'Save Changes' : 'Add Customer'}
                           </Button>
                       </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </CardHeader>
        {/* Customer Table Content */}
        <CardContent className="p-0">
          {loading ? (
             <div className="flex justify-center items-center py-16 text-muted-foreground">
                <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                 <span>Loading customers...</span>
             </div>
          ) : customers.length === 0 ? (
              // Empty State Message
              <div className="text-center py-16 px-6">
                 <Users className="mx-auto h-12 w-12 text-muted-foreground/50 mb-4" />
                 <p className="text-muted-foreground font-medium mb-2">No customers found.</p>
                 <p className="text-muted-foreground text-sm mb-4">Click "Add Customer" to get started.</p>
                 {/* Button to open the add form */}
                 <Button onClick={() => handleOpenForm()}>
                    <UserPlus className="mr-2 h-4 w-4" /> Add First Customer
                 </Button>
             </div>
          ) : (
            // Customer Table
            <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Phone</TableHead>
                      <TableHead className="hidden md:table-cell">Address</TableHead>
                      <TableHead className="text-center">Trust</TableHead>
                      <TableHead className="text-right">Credit Limit</TableHead>
                       <TableHead className="hidden lg:table-cell text-right">Added On</TableHead>
                      {/* Sticky Actions Column */}
                      <TableHead className="text-right sticky right-0 bg-card z-10 px-2 md:px-4">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {customers.map((customer) => (
                      <TableRow key={customer._id} className="hover:bg-muted/50">
                        <TableCell className="font-medium">{customer.name}</TableCell>
                        <TableCell>{customer.phone}</TableCell>
                        <TableCell className="hidden md:table-cell max-w-xs truncate text-muted-foreground">{customer.address || 'N/A'}</TableCell>
                        <TableCell className="text-center">{customer.trustScore}/10</TableCell>
                        {/* Format currency */}
                        <TableCell className="text-right">₹{Number(customer.creditLimit).toFixed(2)}</TableCell>
                        {/* Format date */}
                        <TableCell className="hidden lg:table-cell text-right text-sm text-muted-foreground">
                            {format(new Date(customer.createdAt), 'dd MMM yyyy')}
                        </TableCell>
                        {/* Action Buttons - Sticky */}
                        <TableCell className="text-right space-x-1 sticky right-0 bg-card z-10 px-2 md:px-4">
                            {/* Edit Button */}
                            <Button variant="ghost" size="icon" className="hover:text-primary h-8 w-8" onClick={() => handleOpenForm(customer)} title="Edit">
                                <Edit className="h-4 w-4" />
                                 <span className="sr-only">Edit</span>
                            </Button>
                            {/* Delete Button */}
                            <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive/80 h-8 w-8" onClick={() => openDeleteDialog(customer)} title="Delete">
                                <Trash2 className="h-4 w-4" />
                                 <span className="sr-only">Delete</span>
                            </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
            </div>
           )}
        </CardContent>
         {/* Optional: Add pagination controls if list becomes long */}
         {/* <CardFooter className="p-4 border-t"> <PaginationComponent /> </CardFooter> */}
      </Card>


      {/* Delete Confirmation Dialog */}
       <Dialog open={isDeleteDialogOpen} onOpenChange={(open) => open ? setIsDeleteDialogOpen(true) : closeDeleteDialog()}>
         <DialogContent
             onInteractOutside={(e) => { if (isDeleting) e.preventDefault(); }}
             onEscapeKeyDown={(e) => { if (isDeleting) e.preventDefault(); }}
         >
             <DialogHeader>
                 <DialogTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-destructive"/> Confirm Deletion</DialogTitle>
                 {/* Alert inside the dialog for emphasis */}
                 <Alert variant="destructive" className="mt-4 border-0 bg-transparent p-0">
                     <AlertDescription>
                         This action will permanently delete the customer <strong className="text-foreground">"{customerToDelete?.name}"</strong>.
                         This cannot be undone. Ensure the customer has no outstanding loans before deleting.
                     </AlertDescription>
                 </Alert>
             </DialogHeader>
             {/* Dialog Footer for Delete Confirmation */}
             <DialogFooter className="mt-4">
                <Button variant="outline" onClick={closeDeleteDialog} disabled={isDeleting}>Cancel</Button>
                <Button variant="destructive" onClick={handleDelete} disabled={isDeleting}>
                    {isDeleting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    Delete Customer
                </Button>
             </DialogFooter>
         </DialogContent>
       </Dialog>
    </div>
  );
}
